### ISSUE TITLE
How to find the hyp base address and RPM reset address for other SoC?

### ISSUE THREAD

**Issue by linsite** [msm8916-mainline/qhypstub#4]
Hi, I'm interested in trying to port `qhypstub` to msm8953 for my old phone Xiaomi Redmi 6 Pro. But I don't know how the find the two addresses mentioned in README . Would someone be so kind to tell me that if there  are any documents available？

Thanks a lot!

**Comment by stephan-gh** [comment]
> Would someone be so kind to tell me that if there are any documents available？

Sadly the Snapdragon 410 is pretty much the only Qualcomm chipset with a basic set of public documentation. I'm not aware of any public documentation for MSM8953. :(

However, if I remember correctly the main problem you will have on MSM8953 is that it actually does not have a separate `hyp` firmware. The hypervisor level is likely skipped in the `tz` firmware, or something like that. You can verify this by checking if your device has a `hyp` partition.

**Comment by linsite** [comment]
I've tried. You're right, there isn't a `hyp` partition on my device.

```
$ fastboot erase hyp
erasing 'hyp'...
FAILED (remote: Partition table doesn't exist
)
finished. total time: 0.031s
```

Thanks anyway. I'll close this issue.
