### ISSUE TITLE
Can you add support more chip set ?

### ISSUE THREAD

**Issue by Saikatsaha1996** [msm8916-mainline/qhypstub#6]
Msm 8937 && sdm 865 ..
My bad.. i already enabled KVM but not get success 😞
Please help

**Comment by stephan-gh** [comment]
I think MSM8937 does not have separate `hyp` firmware like MSM8953 (see https://github.com/msm8916-mainline/qhypstub/issues/4).

SD865 is a lot newer and probably quite different, so while a similar approach might work for it I don't know how hard it would be to enable it there.

And remember, you need a device without (firmware) secure boot which is probably the most difficult part for all these newer devices. Sorry.

**Comment by Saikatsaha1996** [comment]
Is it true android 13 has full KVM support ?
https://www.google.com/url?sa=t&source=web&rct=j&url=https://arstechnica.com/gadgets/2022/02/android-13-virtualization-hack-runs-windows-and-doom-in-a-vm-on-android/%3Famp%3D1&ved=2ahUKEwjaitu8mKX5AhVoZWwGHVqPAVsQFnoECDcQAQ&usg=AOvVaw2l2CmJua12exEus0EZorGg

https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.xda-developers.com/android-13-dp1-google-pixel-6-kvm-virtual-machine/amp/&ved=2ahUKEwjaitu8mKX5AhVoZWwGHVqPAVsQFnoECEwQAQ&usg=AOvVaw0LqGCYTnBv-OY6jchJVwsF

**Comment by stephan-gh** [comment]
I've read that as well but I haven't heard anything yet how Qualcomm has dealt (or is going to deal) with this. Maybe it will still be optional for a while giving Qualcomm some time.

**Comment by Saikatsaha1996** [comment]
@stephan-gh i want help personally.. i found in my kernel to many KVM feature already enable.. kernel version 4.19 .. even hyp option also enable in default.. lineage os kernel android 12 .. UFIE run time support disabled.. can you share some time for me please?..

Please see all images and all options ..

![IMG_20220815_012127](https://user-images.githubusercontent.com/72664192/184553102-e3f85677-6128-45d0-b296-b3c8e01070ed.jpg)


![IMG_20220815_011951](https://user-images.githubusercontent.com/72664192/184553104-fba52a4f-7f4b-4da0-ac26-9c7a1e683a6c.jpg)
![IMG_20220815_012029](https://user-images.githubusercontent.com/72664192/184553106-68c68a50-b8ac-481a-8d50-1c4b46bbd58c.jpg)




![IMG_20220815_012459](https://user-images.githubusercontent.com/72664192/184553096-be028807-6fa2-47f4-bd34-957a053f2a0d.jpg)
![IMG_20220815_012321](https://user-images.githubusercontent.com/72664192/184553099-f96b3c09-7d00-4b5e-b5f8-80e99e3dec03.jpg)
![IMG_20220815_012303](https://user-images.githubusercontent.com/72664192/184553100-7f180485-2f4b-4bbb-b168-d0d41b408b9e.jpg)

**Comment by stephan-gh** [comment]
The kernel configuration is the second step. The important part is if the underlying firmware (usually proprietary) starts the kernel in EL2 (hypervisor level) instead of EL1 (kernel level). You can see if that happens or not in the kernel dmesg (e.g. `All CPUs started at EL2` or something like that).

**Comment by Saikatsaha1996** [comment]
> The kernel configuration is the second step. The important part is if the underlying firmware (usually proprietary) starts the kernel in EL2 (hypervisor level) instead of EL1 (kernel level). You can see if that happens or not in the kernel dmesg (e.g. `All CPUs started at EL2` or something like that).

How can I check can you please tell me ? Actually i am a noob about this project..

**Comment by Saikatsaha1996** [comment]
> Check the kernel log (dmesg).

Actually i am not rooted showing 
dmesg: read kernel buffer failed: Function not implemented

**Comment by Saikatsaha1996** [comment]
@stephan-gh mey be KVM is possible.. i also inform u after 78 hours.. 

https://github.com/edk2-porting/EDK2-SM8250

**Comment by Saikatsaha1996** [comment]
@stephan-gh i found in my device frimware i unpack it and found hyp.mbn frimware.. mey be it is hyp partition frimware?

Is it okay?

![Screenshot_2022-08-27-00-39-18-678_ru zdevs zarchiver](https://user-images.githubusercontent.com/72664192/186975172-fc9a510d-0204-46af-b28b-3229ddc0cda8.jpg)

**Comment by stephan-gh** [comment]
If this is the SD865 the following still applies:

> SD865 is a lot newer and probably quite different, so while a similar approach might work for it I don't know how hard it would be to enable it there.
>
> And remember, you need a device without (firmware) secure boot which is probably the most difficult part for all these newer devices. Sorry.

**Comment by Saikatsaha1996** [comment]
> If this is the SD865 the following still applies:
> 
> > SD865 is a lot newer and probably quite different, so while a similar approach might work for it I don't know how hard it would be to enable it there.
> > And remember, you need a device without (firmware) secure boot which is probably the most difficult part for all these newer devices. Sorry.

Yes this is sd865 and this is stock miui frimware

**Comment by Saikatsaha1996** [comment]
@stephan-gh now I confirmed you in snapdragon 865 (sm8250) chipset have hyp partition..
I checked by ( fastboot erase hyp ) erasing done ! completed!

**Comment by Saikatsaha1996** [comment]
@stephan-gh maximum sd 800 series chipset have hyperv partition by default..

**Comment by Saikatsaha1996** [comment]
@stephan-gh dear still now i am waiting..
I have hyp partition in my device..

**Comment by kasnria001** [comment]
> @stephan-gh dear still now i am waiting.. I have hyp partition in my device..

Do you succeed?Your miui device has no secure boot?Unbelievable!

**Comment by Saikatsaha1996** [comment]
> > @stephan-gh dear still now i am waiting.. I have hyp partition in my device..
> 
> Do you succeed?Your miui device has no secure boot?Unbelievable!

I was by mistakely bricked my device..
Because i tried `fastboot erase hyp` erasing done 😃
Than i recover with `EDL mode`.. but i confirm that in my device has `hyp` partition

**Comment by kasnria001** [comment]
> > > @stephan-gh dear still now i am waiting.. I have hyp partition in my device..
> > 
> > 
> > Do you succeed?Your miui device has no secure boot?Unbelievable!
> 
> I was by mistakely bricked my device.. Because i tried `fastboot erase hyp` erasing done 😃 Than i recover with `EDL mode`.. but i confirm that in my device has `hyp` partition

Oh,so although it has hyp,you can not use virtualization because of secure boot?

Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running

**Comment by Saikatsaha1996** [comment]
> > > > @stephan-gh dear still now i am waiting.. I have hyp partition in my device..
> > > 
> > > 
> > > Do you succeed?Your miui device has no secure boot?Unbelievable!
> > 
> > 
> > I was by mistakely bricked my device.. Because i tried `fastboot erase hyp` erasing done 😃 Than i recover with `EDL mode`.. but i confirm that in my device has `hyp` partition
> 
> Oh,so although it has hyp,you can not use virtualization because of secure boot?
> 
> Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running

Check my miui 13 stock firmware..
In my device firmware also you can see `hyp.mbn`

![186975172-fc9a510d-0204-46af-b28b-3229ddc0cda8](https://user-images.githubusercontent.com/72664192/202849757-682114be-a2e5-4c10-b19a-898c6f8a6c17.jpg)

**Comment by kasnria001** [comment]
yes , But this is useless,right? Because you can not flash your own hyp?
&nbsp;


最美的云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月19日(星期六) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6)





     
@stephan-gh dear still now i am waiting.. I have hyp partition in my device..
  
Do you succeed?Your miui device has no secure boot?Unbelievable!
  
I was by mistakely bricked my device.. Because i tried fastboot erase hyp erasing done 😃 Than i recover with EDL mode.. but i confirm that in my device has hyp partition
  
Oh,so although it has hyp,you can not use virtualization because of secure boot?
 
Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running
  
Check my miui 13 stock firmware..
 In my device firmware also you can see hyp.mbn

**Comment by Saikatsaha1996** [comment]
> yes , But this is useless,right? Because you can not flash your own hyp? &nbsp; 最美的云 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月19日(星期六) 晚上8:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6) @stephan-gh dear still now i am waiting.. I have hyp partition in my device.. Do you succeed?Your miui device has no secure boot?Unbelievable! I was by mistakely bricked my device.. Because i tried fastboot erase hyp erasing done  Than i recover with EDL mode.. but i confirm that in my device has hyp partition Oh,so although it has hyp,you can not use virtualization because of secure boot? Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running Check my miui 13 stock firmware.. In my device firmware also you can see hyp.mbn — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I really don't know about it..  because i am confused mey be not possible or posible.. 🥺

**Comment by kasnria001** [comment]
> > yes , But this is useless,right? Because you can not flash your own hyp?   最美的云 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年11月19日(星期六) 晚上8:00 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6) @stephan-gh dear still now i am waiting.. I have hyp partition in my device.. Do you succeed?Your miui device has no secure boot?Unbelievable! I was by mistakely bricked my device.. Because i tried fastboot erase hyp erasing done  Than i recover with EDL mode.. but i confirm that in my device has hyp partition Oh,so although it has hyp,you can not use virtualization because of secure boot? Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running Check my miui 13 stock firmware.. In my device firmware also you can see hyp.mbn — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> I really don't know about it.. because i am confused mey be not possible or posible.. 🥺

I have same ideas at first,but then I give up because it's too difficult,because qualcomm has improved its security greatly since these years ,I think if you want to achieve it,you can try other chips such as Huawei Hisilicon,because it is new and can be hacked easily.

**Comment by Saikatsaha1996** [comment]
> > > yes , But this is useless,right? Because you can not flash your own hyp?   最美的云 _**@**_.***  
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年11月19日(星期六) 晚上8:00 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6) @stephan-gh dear still now i am waiting.. I have hyp partition in my device.. Do you succeed?Your miui device has no secure boot?Unbelievable! I was by mistakely bricked my device.. Because i tried fastboot erase hyp erasing done  Than i recover with EDL mode.. but i confirm that in my device has hyp partition Oh,so although it has hyp,you can not use virtualization because of secure boot? Only if you can write a lk2nd for this chip and find some bugs to replace the hyp in the RAM to jump to the EL2 when running Check my miui 13 stock firmware.. In my device firmware also you can see hyp.mbn — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > I really don't know about it.. because i am confused mey be not possible or posible.. 🥺
> 
> I have same ideas at first,but then I give up because it's too difficult,because qualcomm has improved its security greatly since these years ,I think if you want to achieve it,you can try other chips such as Huawei Hisilicon,because it is new and can be hacked easily.

Dear i was think i move to tensor but performance not good..
Now only better chipset Dimensity is my fast preference & Qualcomm..
But honestly i never used MTK chipset..

**Comment by kasnria001** [comment]
> 

in fact mtk has no new documentaries open for us ,so unlocking the botloader of mtk devices is very difficult , why we can see the unlocking guide is because some security research has shown some bugs,so we have a tool to achieve it.

But for newer chips of mtk, they have fixed this bug.

**Comment by kasnria001** [comment]
@Saikatsaha1996

**Comment by Saikatsaha1996** [comment]
> > 
> 
> in fact mtk has no new documentaries open for us ,so unlocking the botloader of mtk devices is very difficult , why we can see the unlocking guide is because some security research has shown some bugs,so we have a tool to achieve it.
> 
> But for newer chips of mtk, they have fixed this bug.

But i am really impressed with MTK Dimensity chipset..

**Comment by kasnria001** [comment]
Yes.

But sometimes I feel unfair and upset because I have spent so much money buying a phone or tablet with good performance chips ,but it can only run android instead of linux or windows Arm64&nbsp;
&nbsp;


最美的云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月19日(星期六) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6)





    
in fact mtk has no new documentaries open for us ,so unlocking the botloader of mtk devices is very difficult , why we can see the unlocking guide is because some security research has shown some bugs,so we have a tool to achieve it.
 
But for newer chips of mtk, they have fixed this bug.
  
But i am really impressed with MTK Dimensity chipset..

**Comment by Saikatsaha1996** [comment]
> Yes. But sometimes I feel unfair and upset because I have spent so much money buying a phone or tablet with good performance chips ,but it can only run android instead of linux or windows Arm64&nbsp; &nbsp; 最美的云 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月19日(星期六) 晚上8:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [msm8916-mainline/qhypstub] Can you add support more chip set ? (Issue #6) in fact mtk has no new documentaries open for us ,so unlocking the botloader of mtk devices is very difficult , why we can see the unlocking guide is because some security research has shown some bugs,so we have a tool to achieve it. But for newer chips of mtk, they have fixed this bug. But i am really impressed with MTK Dimensity chipset.. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

If you have c c++ knowledge you can add your Android device kernel to mainline.. than you can boot into linux

**Comment by Saikatsaha1996** [comment]
> If this is the SD865 the following still applies:
> 
> > SD865 is a lot newer and probably quite different, so while a similar approach might work for it I don't know how hard it would be to enable it there.
> > And remember, you need a device without (firmware) secure boot which is probably the most difficult part for all these newer devices. Sorry.

@stephan-gh sir please check

In my device kernel tree i have hyp memory data & even i have hyp partition in my device..
My kernel version 5.4 and i saw in my kernel have option Qualcomm virtual machine support available but it is disabled.. can it possible to run KVM hardware support?

https://github.com/pjgowtham/android_kernel_oneplus_sm8350/blob/ffa3efd23c005672bff907f71a619dfd9cf82aec/arch/arm64/boot/dts/vendor/qcom/lahaina.dtsi#L402

https://github.com/pjgowtham/android_kernel_oneplus_sm8350/blob/ffa3efd23c005672bff907f71a619dfd9cf82aec/arch/arm64/boot/dts/vendor/qcom/lahaina.dtsi#L307


![IMG_20230519_004830](https://github.com/msm8916-mainline/qhypstub/assets/72664192/f1ae2b35-6a00-430a-b468-7a3917a9508a)
![IMG_20230519_004816](https://github.com/msm8916-mainline/qhypstub/assets/72664192/2388e416-1420-4017-ae62-7c9afe9a19c3)

**Comment by Saikatsaha1996** [comment]
We have inbuilt hypervisor support for newer Snapdragon SoC ?

![IMG_20230624_084240](https://github.com/msm8916-mainline/qhypstub/assets/72664192/cc9ac7f1-ced2-418e-90e4-2eb5d73a1348)

**Comment by kasnria001** [comment]
> 我们为较新的骁龙 SoC 提供了内置的虚拟机管理程序支持？
> 
> ![IMG_20230624_084240](https://user-images.githubusercontent.com/72664192/248440364-cc9ac7f1-ced2-418e-90e4-2eb5d73a1348.jpg)

Yes but I don't know how to configure it.

**Comment by Saikatsaha1996** [comment]
https://developer.arm.com/documentation/100942/0100/AArch64-virtualization?lang=en

[whitepaper_0.pdf](https://github.com/msm8916-mainline/qhypstub/files/11859649/whitepaper_0.pdf)
https://github.com/quic/gunyah-hypervisor.git

Okay so Qualcomm released there hypervisor support fast in Snapdragon 888 platform 😁

**Comment by Saikatsaha1996** [comment]
Wooww just rooted stock device.. all cpu started at EL1...

Chipset sm8350 has inbuilt hypervisor
![IMG_20230803_171533](https://github.com/msm8916-mainline/qhypstub/assets/72664192/e5912a22-70ef-4789-834f-0a0cbfc70bed)

Dmsg text

[dmesg.txt](https://github.com/msm8916-mainline/qhypstub/files/12250426/dmesg.txt)

**Comment by kasnria001** [comment]
> Wooww just rooted stock device.. all cpu started at EL1...
> 
> Chipset sm8350 has inbuilt hypervisor ![IMG_20230803_171533](https://user-images.githubusercontent.com/72664192/258101442-e5912a22-70ef-4789-834f-0a0cbfc70bed.jpg)
> 
> Dmsg text
> 
> [dmesg.txt](https://github.com/msm8916-mainline/qhypstub/files/12250426/dmesg.txt)

Well.But you need to find the documantation about qualcomm hypervisor.I think they are open.

**Comment by Saikatsaha1996** [comment]
> > Wooww just rooted stock device.. all cpu started at EL1...
> > Chipset sm8350 has inbuilt hypervisor ![IMG_20230803_171533](https://user-images.githubusercontent.com/72664192/258101442-e5912a22-70ef-4789-834f-0a0cbfc70bed.jpg)
> > Dmsg text
> > [dmesg.txt](https://github.com/msm8916-mainline/qhypstub/files/12250426/dmesg.txt)
> 
> Well.But you need to find the documantation about qualcomm hypervisor.I think they are open.

Yes i got it.. 

https://github.com/quic/gunyah-hypervisor.git
