### ISSUE TITLE
open question: will this work on a 4g lte usb modem?

### ISSUE THREAD

**Issue by colemickens** [msm8916-mainline/qhypstub#9]
https://extrowerk.com/2022/07/31/OpenStick/

I'm tempted to go dig mine out, see if it's a SD410 and see if this works...

**Comment by stephan-gh** [comment]
In general I would expect: yes. AFAIK it does not have (firmware) secure boot enabled. There are still two "challenges" (not problems):

- I think it has 32-bit firmware by default, so you'd need to replace parts of its firmware with 64-bit ones from other devices (e.g. DragonBoard 410c)
- It has just 512 MiB of RAM so doing (Linux) virtualization there probably won't be much fun :)

**Comment by colemickens** [comment]
turns out it already does: https://github.com/OpenStick/OpenStick/issues/11 and hopefully my experience with adapting nixos to all sorts of weird places should make it easy to build a root fs (mobile-nixos might make it even easier as it already supports building targeting android type devices). anyway...

thanks for `qhypstub`, I was looking at this for phone-related stuff months ago and figured I'd never wind up using it and now I'm about to have access $9 4g-enabled wifi embedded devices that can run linux and kvm. Very cool, thank you!
